### ISSUE TITLE
Where exactly can I disable the towny integration ?If there is no option in QA config.

### ISSUE THREAD

**Issue by bedrye** [ZombieStriker/QualityArmory#227]

**Comment by Lorenzo0111** [comment]
Can you send me your configuration file?

**Comment by bedrye** [comment]
```
ENABLE-DEBUG: false
language: en
FriendlyFireEnabled: true
KickPlayerIfDeniedResourcepack: false
useDefaultResourcepack: true
EnableWeaponDurability: true
BulletDetection:
  step: 0.1
BlockBullets:
  door: false
  halfslabs: false
  leaves: false
  water: false
  glass: false
enableInteract:
  Chests: false
overrideAnvil: true
showPossibleCrashHelpMessage: true
verboseItemLogging: false
enable_permssionsToShoot: false
sendOnJoin: true
sendTitleOnJoin: false
SecondsTillRPIsSent: 5.0
enableBulletTrails: true
BulletTrailsSpacing: 0.5
enableIgnoreArmorProtection: false
enableIgnoreUnbreakingChecks: false
enableIgnoreSkipForBasegameItems: false
Items:
  enable_Unbreaking: true
enableReloadingWhenSwapToOffhand: true
enableReloadOnlyWhenSwapToOffhand: false
allowGunHitEntities: true
showOutOfAmmoOnTitle: false
showReloadingTitle: false
showAmmoInXPBar: false
enableExplosionDamage: false
enableExplosionDamageDrop: false
enablePrimaryWeaponLimiter: false
weaponlimiter_primaries: 2
weaponlimiter_secondaries: 2
enableCrafting: false
enableShop: false
AUTO-UPDATE: true
Swap-Reload-and-Shooting-Controls: false
Order-Shop-By-Price: false
enable_lore_gun-info_messages: true
enable_lore_control-help_messages: true
Enable_Headshot_Instantkill: true
Enable_Headshot_Notification_Sound: true
Headshot_Notification_Sound: entity.experience_orb.pickup
Enable_Headshot_Sounds: true
Enable_AutoArm_Grenades: false
gravityConstantForDropoffCalculations: 0.05
allowGunReload: true
Auto-Detect-Resourcepack: true
ManuallyOverrideTo_1_8_systems: false
ManuallyOverrideTo_1_13_systems: false
ManuallyOverrideTo_1_14_systems: false
unknownTranslationKeyFixer: false
Enable_Creation_Of_Default_Files: true
EnableGlowEffects: false
Break-Block-Texture-If-Shot: true
enableRecoil: true
experimental:
  BulletWounds:
    InitialBloodLevel: 1500.0
    BloodIncreasePerSecond: 0.01
    Medkit_Heal_Bloodloss_Rate: 0.05
    enableBleeding: false
disableHotbarMessages:
  OutOfAmmo: false
  Shoot: false
  Reload: false
automaticallyReloadGunWhenOutOfAmmo: false
generalModifiers:
  sway:
    Run: 2.0
    Walk: 1.5
    Ironsights: 0.8
    Sneak: 0.7
deathmessages:
  enable: true
impenetrableEntityTypes:
- ARROW
IronSightsOnRightClick: false
SwapSneakToSingleFire: false
DestructableMaterials:
- MATERIAL_NAME_HERE
DefaultResourcepackOverride: true
DefaultResourcepack: https://www.dropbox.com/s/pg8bgpigqeh5k04/QualityArmoryV2.1.8.zip?dl=1
enableReloadingOnDrop: true

```
