### ISSUE TITLE
BurstFire is broken

### ISSUE THREAD

**Issue by GitGraf** [ZombieStriker/QualityArmory#72]
Version: 1.1.160
When using the `ChargingHandler: BurstFire`, the damage per shot is too high.

```yml
name: m4a1sburst
displayname: '&6M4A1s (Burst)'
id: 25
variant: 1
craftingRequirements:
- IRON_INGOT,0,15
- REDSTONE,0,5
weapontype: RIFLE
weaponsounds: bulletmedium
_VALID_WEAPON_TYPES: 'PISTOL, SMG, RPG, RIFLE, SHOTGUN, FLAMER, SNIPER, BIG_GUN, GRENADES,
  SMOKE_GRENADES, FLASHBANGS, INCENDARY_GRENADES, MINES, MELEE, MISC, AMMO, HELMET,
  MEDKIT, LAZER, '
enableIronSights: true
ammotype: '556'
damage: 3
maxbullets: 30
price: 3600
ChargingHandler: BurstFire
firerate: 3
bullets-per-shot: 3
material: CROSSBOW
recoil: 1.0
invalid: false
durability: 1000
setZoomLevel: 0
sway: 0.2
delayForReload: 1.5
delayForShoot: 0.3
isAutomatic: false
maxBulletDistance: 200
unlimitedAmmo: false
LightLeveOnShoot: 14
particles:
  bullet_particle: REDSTONE
  bullet_particleR: 1
  bullet_particleG: 1
  bullet_particleB: 1
  bullet_particleMaterial: COAL_BLOCK
Version_18_Support: false
addMuzzleSmoke: true
drop-glow-color: none
headshotMultiplier: 3.5
swayMultiplier: 2
weaponsounds_volume: 4
lastModifiedByQA: 1584888692299
```
For **every shot**, 9 damage is instantly applied to the entity (rather than the configured "damage" of 3).
EDIT: Also just noticed that the single fire mode is also not working correctly with burst fire.
